plugins:
  - prettier-plugin-tailwindcss

# tabWidth: <inherited from .editorconfig>
# useTabs: <inherited from .editorconfig>
# endOfLine: <inherited from .editorconfig>
semi: true
singleQuote: true
jsxSingleQuote: true
bracketSpacing: false
tailwindFunctions: ['clsx']
tailwindStylesheet: './src/styles/global.css'
